import type { Profile } from './types';
import { createUserProfile } from './db';

export const profiles: Profile[] = [
  {
    id: '1',
    name: 'Priya Patel',
    age: 28,
    gender: 'Female',
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    photos: [
      { id: '1', url: 'https://picsum.photos/seed/prof1/400/400', hint: 'woman portrait' },
      { id: '13', url: 'https://picsum.photos/seed/prof13/600/800', hint: 'woman hiking' },
      { id: '14', url: 'https://picsum.photos/seed/prof14/600/800', hint: 'woman gallery' },
    ],
    bio: 'Software engineer with a love for the outdoors. I enjoy hiking, trying new food trucks, and weekend trips. Looking for someone with a good sense of humor and a kind heart.',
    interests: ['Hiking', 'Cooking', 'Technology', 'Travel', 'Live Music'],
    occupation: 'Software Engineer',
    education: 'Masters in Computer Science',
    height: "5'6\"",
    religionInfo: { religion: 'Hindu', caste: 'Patel' },
    familyDetails: { bio: 'From a close-knit family based in Mumbai. Parents are retired, and I have one older brother.' },
    partnerPreferences: {
      ageRange: '28-35',
      heightRange: "5'9\" - 6'2\"",
      bio: 'Seeking an ambitious and caring partner who values family and is open to adventure.',
      interests: ['Travel', 'Technology', 'Outdoors'],
    },
  },
  {
    id: '2',
    name: 'Rohan Sharma',
    age: 32,
    gender: 'Male',
    location: { city: 'New York', state: 'NY', country: 'USA' },
    photos: [{ id: '2', url: 'https://picsum.photos/seed/prof2/400/400', hint: 'man portrait' }],
    bio: 'Investment banker by day, musician by night. I find balance in life through my passion for jazz music and exploring the city\'s vibrant culture. Looking for a genuine connection.',
    interests: ['Jazz Music', 'Finance', 'Reading', 'Museums', 'Fine Dining'],
    occupation: 'Investment Banker',
    education: 'MBA in Finance',
    height: "6'0\"",
    religionInfo: { religion: 'Hindu', caste: 'Brahmin' },
    familyDetails: { bio: 'My family lives in Delhi. Father is a doctor, mother is a professor.' },
    partnerPreferences: {
      ageRange: '27-33',
      heightRange: "5'5\" - 5'10\"",
      bio: 'Looking for an intelligent, independent woman who is passionate about her career and hobbies.',
      interests: ['Arts', 'Culture', 'Reading'],
    },
  },
  {
    id: '3',
    name: 'Chloe Kim',
    age: 26,
    gender: 'Female',
    location: { city: 'Los Angeles', state: 'CA', country: 'USA' },
    photos: [{ id: '3', url: 'https://picsum.photos/seed/prof3/400/400', hint: 'person hiking' }],
    bio: 'Graphic designer and artist. I love everything related to visual arts, from digital design to painting. My ideal weekend involves a trip to the beach, followed by a cozy movie night.',
    interests: ['Art', 'Graphic Design', 'Beach', 'Movies', 'Yoga'],
    occupation: 'Graphic Designer',
    education: 'BFA in Graphic Design',
    height: "5'4\"",
    religionInfo: { religion: 'Christian', caste: 'N/A' },
    familyDetails: { bio: 'Grew up in Seoul, moved to LA for college. My parents and younger sister still live in Korea.' },
    partnerPreferences: {
      ageRange: '26-34',
      heightRange: "5'8\" - 6'1\"",
      bio: 'Searching for a creative and supportive partner to share life\'s adventures with.',
      interests: ['Art', 'Music', 'Travel'],
    },
  },
  {
    id: '4',
    name: 'Aarav Singh',
    age: 30,
    gender: 'Male',
    location: { city: 'Chicago', state: 'IL', country: 'USA' },
    photos: [{ id: '4', url: 'https://picsum.photos/seed/prof4/400/400', hint: 'woman reading' }],
    bio: 'Architect with a passion for sustainable design. I enjoy cycling along the lakefront, exploring new neighborhoods, and sketching buildings. Looking for a witty and thoughtful partner.',
    interests: ['Architecture', 'Cycling', 'Sustainability', 'Photography'],
    occupation: 'Architect',
    education: 'Masters in Architecture',
    height: "5'11\"",
    religionInfo: { religion: 'Sikh', caste: 'Khatri' },
    familyDetails: { bio: 'My family is from Punjab. We are a modern family with traditional values.' },
    partnerPreferences: {
      ageRange: '27-32',
      heightRange: "5'5\"+",
      bio: 'Hoping to meet someone who is intellectually curious, kind, and enjoys deep conversations.',
      interests: ['Design', 'Arts', 'Travel'],
    },
  },
  {
    id: '5',
    name: 'Meera Iyer',
    age: 29,
    gender: 'Female',
    location: { city: 'Austin', state: 'TX', country: 'USA' },
    photos: [{ id: '5', url: 'https://picsum.photos/seed/prof5/400/400', hint: 'man guitar' }],
    bio: 'Doctor in residency. Life is busy, but I make time for things I love: live music, paddleboarding, and my golden retriever. Looking for someone who is patient, driven, and loves dogs.',
    interests: ['Medicine', 'Live Music', 'Paddleboarding', 'Dogs', 'Brunch'],
    occupation: 'Doctor',
    education: 'MD',
    height: "5'7\"",
    religionInfo: { religion: 'Hindu', caste: 'Iyer' },
    familyDetails: { bio: 'Born and raised in Chennai. My parents are both academics.' },
    partnerPreferences: {
      ageRange: '29-36',
      heightRange: "5'10\"+",
      bio: 'Seeking a supportive and understanding partner who can handle my hectic schedule and share a laugh.',
      interests: ['Outdoors', 'Music', 'Dogs'],
    },
  },
  {
    id: '6',
    name: 'David Chen',
    age: 34,
    gender: 'Male',
    location: { city: 'Seattle', state: 'WA', country: 'USA' },
    photos: [{ id: '6', url: 'https://picsum.photos/seed/prof6/400/400', hint: 'woman laughing' }],
    bio: 'Data scientist at a tech company. I\'m an analytical thinker but have a creative side. I love hiking in the Cascades, brewing my own coffee, and playing board games. Looking for an adventurous and easy-going partner.',
    interests: ['Data Science', 'Hiking', 'Coffee', 'Board Games', 'Sci-Fi'],
    occupation: 'Data Scientist',
    education: 'PhD in Statistics',
    height: "5'9\"",
    religionInfo: { religion: 'Agnostic', caste: 'N/A' },
    familyDetails: { bio: 'My parents immigrated from Taiwan. I have one sister who is a chef.' },
    partnerPreferences: {
      ageRange: '28-35',
      heightRange: "5'4\" - 5'9\"",
      bio: 'I\'d love to meet someone who is curious about the world and doesn\'t mind a friendly-competitive game night.',
      interests: ['Hiking', 'Travel', 'Puzzles'],
    },
  },
  {
    id: '7',
    name: 'Ananya Rao',
    age: 27,
    gender: 'Female',
    location: { city: 'Boston', state: 'MA', country: 'USA' },
    photos: [{ id: '7', url: 'https://picsum.photos/seed/prof7/400/400', hint: 'man office' }],
    bio: 'Biotech researcher and a huge history buff. When I\'m not in the lab, I\'m usually at a museum or curled up with a historical fiction novel. Seeking a partner for intellectual sparring and life adventures.',
    interests: ['Biotechnology', 'History', 'Museums', 'Reading', 'Sailing'],
    occupation: 'Researcher',
    education: 'PhD in Biology',
    height: "5'5\"",
    religionInfo: { religion: 'Hindu', caste: 'Rao' },
    familyDetails: { bio: 'Originally from Bangalore. My family values education and open-mindedness.' },
    partnerPreferences: {
      ageRange: '28-35',
      heightRange: "5'10\"+",
      bio: 'Looking for a kind, intelligent man who can teach me new things and is excited to learn from me.',
      interests: ['Science', 'History', 'Travel'],
    },
  },
  {
    id: '8',
    name: 'Karan Malhotra',
    age: 31,
    gender: 'Male',
    location: { city: 'Miami', state: 'FL', country: 'USA' },
    photos: [{ id: '8', url: 'https://picsum.photos/seed/prof8/400/400', hint: 'person painting' }],
    bio: 'Entrepreneur in the hospitality industry. I love the energy of Miami. My passions are sailing, trying new restaurants, and salsa dancing. Looking for a confident and fun-loving partner to enjoy life with.',
    interests: ['Entrepreneurship', 'Sailing', 'Foodie', 'Dancing', 'Beach'],
    occupation: 'Entrepreneur',
    education: 'Bachelors in Business Administration',
    height: "6'1\"",
    religionInfo: { religion: 'Hindu', caste: 'Khatri' },
    familyDetails: { bio: 'My family runs a business in New Jersey. I moved to Miami to start my own venture.' },
    partnerPreferences: {
      ageRange: '26-32',
      heightRange: "5'5\"+",
      bio: 'Seeking a vibrant and adventurous woman who loves to socialize and try new things.',
      interests: ['Travel', 'Dancing', 'Food'],
    },
  },
  {
    id: '9',
    name: 'Sonia Gupta',
    age: 30,
    gender: 'Female',
    location: { city: 'Denver', state: 'CO', country: 'USA' },
    photos: [{ id: '9', url: 'https://picsum.photos/seed/prof9/400/400', hint: 'woman yoga' }],
    bio: 'Environmental lawyer and avid skier. I am passionate about protecting our planet. I spend my free time in the mountains, either skiing, hiking, or camping. Looking for someone who shares my love for nature.',
    interests: ['Environmental Law', 'Skiing', 'Hiking', 'Camping', 'Yoga'],
    occupation: 'Lawyer',
    education: 'Juris Doctor',
    height: "5'8\"",
    religionInfo: { religion: 'Jain', caste: 'Gupta' },
    familyDetails: { bio: 'My family is based in Chicago. They are very supportive of my career and passions.' },
    partnerPreferences: {
      ageRange: '30-38',
      heightRange: "5'10\"+",
      bio: 'Hoping to meet an eco-conscious and active partner who enjoys being outdoors as much as I do.',
      interests: ['Outdoors', 'Sustainability', 'Travel'],
    },
  },
  {
    id: '10',
    name: 'Vikram Reddy',
    age: 33,
    gender: 'Male',
    location: { city: 'Dallas', state: 'TX', country: 'USA' },
    photos: [{ id: '10', url: 'https://picsum.photos/seed/prof10/400/400', hint: 'man cooking' }],
    bio: 'Civil engineer and a dedicated sports fan (Go Cowboys!). I value honesty and a good work ethic. My weekends are for grilling, watching sports, and spending time with family and friends.',
    interests: ['Engineering', 'American Football', 'Grilling', 'Country Music'],
    occupation: 'Civil Engineer',
    education: 'B.S. in Civil Engineering',
    height: "5'10\"",
    religionInfo: { religion: 'Hindu', caste: 'Reddy' },
    familyDetails: { bio: 'I come from a large, traditional family from Hyderabad. Family is very important to me.' },
    partnerPreferences: {
      ageRange: '28-33',
      heightRange: "5'4\" - 5'8\"",
      bio: 'Looking for a family-oriented, down-to-earth woman who enjoys a relaxed lifestyle.',
      interests: ['Family', 'Cooking', 'Movies'],
    },
  },
];

export async function seedProfiles() {
  console.log('Seeding profiles...');
  for (const profile of profiles) {
    try {
      await createUserProfile(profile.id, profile);
      console.log(`Seeded profile: ${profile.name}`);
    } catch (error) {
      console.error(`Error seeding profile ${profile.name}:`, error);
    }
  }
  console.log('Seeding complete!');
}
